### PR TITLE
Package bitrot

### LINKED ISSUE #170: Fix dask issues/errors from #119
In #119 improved dask/distributed support was added. However, this throws a lot of warnings, and ends with an error when the cluster is shutdown. The code seems to work fine, but it would be nice to fix this properly.

### LINKED ISSUE #228: Pydantic version issue
Hi,
This is to flag a potential issue with Pydantic versions, and the work-around that I implemented.
-pat

I have just installed Wam2layers on a new computer (Macbook Pro, 2023), and during the initial run of the wam2layers, I received the following error: 
image

The error suggested that @root_validator in Pydantic was deprecated, so I went to the Pydantic docs here: https://docs.pydantic.dev/dev-v2/usage/errors/#root-validator-pre-skip
Then, I looked into the Migration Guide: https://docs.pydantic.dev/dev-v2/migration/

Based on the suggestion on this page, I tried installing an earlier version of Pydantic (pip install "pydantic==1.*"). This, uninstalled pydantic 2.0.2, and installed pydantic version 1.10.11.

After this, the wam2layers code ran without error.

### PR DESCRIPTION
**Pull request by Peter9192**
- Add continuous integration (CI) workflow to install the package and run a test case (for multiple python versions)
- Upgrade to pydantic v2 (fixes #228) (see https://docs.pydantic.dev/latest/migration/)
- Use newer versions of dask and distributed (fixes #170)
- Release version pins in pyproject.toml

Also I noticed the docs build for the Configuration API failed on current RTD page, but in this PR it is properly rendered again.

### CODE REVIEW

**Comment by Peter9192** [comment]
@ruudvdent or @Imme1992 can you try to make a fresh install of the package (ideally with python 3.10 or 3.11) and test if the code still works for you?

**Comment by ruudvdent** [comment]
could not really check it because the main still has the python <-3.10 requirement and I installed 3.11

`ERROR: Package 'wam2layers' requires a different Python: 3.11.4 not in '<3.10,>=3.8'
(wamenv2) rjvanderent@TUD256284:~/WAM2layers_test_versions/WAM2layers$ wam2layers
wam2layers: command not found
(wamenv2) rjvanderent@TUD256284:~/WAM2layers_test_versions/WAM2layers$ pip install wam2layers
ERROR: Ignored the following versions that require a different python version: 3.0.0b2 Requires-Python <3.10,>=3.8; 3.0.0b3 Requires-Python <3.10,>=3.8; 3.0.0b4 Requires-Python <3.10,>=3.8
ERROR: Could not find a version that satisfies the requirement wam2layers (from versions: none)
ERROR: No matching distribution found for wam2layers`

I will just approve it, so anyone can use WAM2layers with newer python releases

**Review by ruudvdent — APPROVED** [review]

**Comment by ruudvdent** [comment]
ok, now properly tested and works. @Peter9192 all set to merge!

**Comment by Peter9192** [comment]
Thanks for reviewing

**Pull request merged**
