### PR TITLE
Add forward tracking

### PR DESCRIPTION
**Pull request by Peter9192**
work in progress

### CODE REVIEW

**Comment by Imme1992** [comment]
On day 20th of June we get negative values for s_track and p_track_upper and p_track_lower which grow into big negative values until the 27th of June. I include the yaml file.

```yaml
# General
log_level: info
preprocessed_data_folder: /projects/0/prjs0202/floodcase_202107_global/preprocessed_data_tcw
output_folder: /projects/0/prjs0202/Euregio_outputdata_forward_oneday
chunks: {time: 1}

# Preprocessing
filename_template: /projects/0/prjs0202/ERA5data/{year}/{month:02}/ERA5_{year}-{month:02d}-{day:02d}{levtype}_{variable}.nc
preprocess_start_date: "2021-06-01T00:00"
preprocess_end_date: "2021-07-16T00:00"
level_type: model_levels
levels: [20,40,60,80,90,95,100,105,110,115,120,123,125,128,130,131,132,133,134,135,136,137]

# Tracking
region: /home/benedicti/cases_wam2layers/source_region_global.nc
track_start_date: "2021-06-01T00:00"
track_end_date: "2021-07-16T00:00"
event_start_date: "2021-06-01T00:00"
event_end_date: "2021-06-01T23:00"
input_frequency: "1h"
target_frequency: "4min"
output_frequency: "1d"
restart: False
periodic_boundary: true
kvf: 3
```

**Comment by Peter9192** [comment]
Merge conflict fixed. Tests running again.

**Comment by Peter9192** [comment]
> we get negative values for s_track

I think I may have found a potential source for this problem, see https://github.com/WAM2layers/WAM2layers/pull/289/commits/0b23f95e30dcac08e1df05e9f94709e608731a9d. The reference time for the stability correction was written the wrong way around (please check my reasoning). Wondering if this fixes the issue.

**Comment by Peter9192** [comment]
> > we get negative values for s_track
> 
> I think I may have found a potential source for this problem, see [0b23f95](https://github.com/WAM2layers/WAM2layers/commit/0b23f95e30dcac08e1df05e9f94709e608731a9d). The reference time for the stability correction was written the wrong way around (please check my reasoning). Wondering if this fixes the issue.

We concluded that this is a good fix, but it doesn't explain the problem. Agreed to merge forward tracking now and further investigate stability problem in #295 and #300.

**Review by Imme1992 — APPROVED** [review]

**Pull request merged**
