### PR TITLE
Read surface data and calculate 2m q

### PR DESCRIPTION
**Pull request by chrisweij**
Calculation of 2 meter specific humidity from dew point temperature and surface pressure.

Also reads in other surface variables (u10 and v10 meter).

### CODE REVIEW

**Review by Peter9192 — APPROVED** [review]
Looks very neat!

**Comment by Peter9192** [comment]
I have solved the merge conflict, feel free to merge it now :-)

**Comment by ruudvdent** [comment]
I will integrate these changes in another pull request

**Review by ruudvdent — COMMENTED** [review]
ok, and will be merged in another branch and pull request

**Pull request closed without merging**
