### PR TITLE
Logging

### LINKED ISSUE #67: Add logging among others about stability criterion affects fluxes (given the time frequency)

### PR DESCRIPTION
**Pull request by Peter9192**
Supersedes #158 

Replaces print statement by calls to logging.info
Write logging.info to terminal and logging.debug to logfile (`wam2layers_<timestamp>.log`)

Should close #67

### CODE REVIEW

**Comment by Peter9192** [comment]
@Imme1992 @ruudvdent in #158 we added prints of all the stability corrections. However this means there's 12 prints per tracked hour (at a time step of 10 minutes). That leads to enormous log files. Can we come up with a smarter approach? For example, only log when the correction exceeds a certain amount?

**Comment by Peter9192** [comment]
After discussion, we settled on the following

1. First time a stability correction is applied for more than 5% of the grid, issue a warning advising to reduce the timestep
2. Subsequently, once the previous correction is exceeded by either 5%point of grid cells, or doubled in magnitude, issue the warning again.

**Comment by Peter9192** [comment]
@Imme1992 @ruudvdent should we track and log the `mean` stability correction of all grid cells or the `maximum`?

**Comment by ruudvdent** [comment]
> @Imme1992 @ruudvdent should we track and log the `mean` stability correction of all grid cells or the `maximum`?

Could we do both? Information could be relevant for different purposes. 

> First time a stability correction is applied for more than 5% of the grid, issue a warning advising to reduce the timestep
    Subsequently, once the previous correction is exceeded by either 5%point of grid cells, or doubled in magnitude, issue the warning again.

Would be useful to for those specific timesteps write out a netcdf-file containing that correction, so I user could inspect at which locations a stability correction is applied.

**Comment by Peter9192** [comment]
> > First time a stability correction is applied for more than 5% of the grid, issue a warning advising to reduce the timestep
> > Subsequently, once the previous correction is exceeded by either 5%point of grid cells, or doubled in magnitude, issue the warning again.
> 
> Would be useful to for those specific timesteps write out a netcdf-file containing that correction, so I user could inspect at which locations a stability correction is applied.

I like that idea, we could also do a dump of the full state or something like that. Does require quite a bit of refactoring though

**Comment by Imme1992** [comment]
I am looking into the logging branch, it looks good, my suggestion so far is to copy the log file to the output folder instead of having it in the working directory folder.

**Review by Imme1992 — COMMENTED** [review]
See my comment in the logging

**Comment by Peter9192** [comment]
Thanks for reviewing! Filename of the correction field is fixed now, and I created https://github.com/WAM2layers/WAM2layers/issues/267 about changing the location of the logfile. Let's pick that up in a follow-up PR

**Review by Imme1992 — APPROVED** [review]

**Pull request merged**
