### PR TITLE
Added logging to backtrack and profiling script

### PR DESCRIPTION
**Pull request by Imme1992**

### CODE REVIEW

**Comment by Imme1992** [comment]
Pull request closes issue #67

**Comment by Imme1992** [comment]
Only calculate the extra variables such as how much moisture is tracked and how often the stability criteria is used when they are also requested by the logger level in the yaml

**Comment by Peter9192** [comment]
I'm afraid that currently with writing out every timestep for DEBUG the log file will be massive. Can you check this?

**Comment by ruudvdent** [comment]
This is not something to merge anymore per #238

**Pull request closed without merging**
