### PR TITLE
Change CLI to `wam2layers track configfile.yml`

### LINKED ISSUE #328: Finalize cli visualize commands, support forwardtracking
Before v3 the interface for visualization should be finalized.

A test for the visualization of forward tracking data should also be added.

### PR DESCRIPTION
**Pull request by BSchilperoort**
Instead of trying to infer the tracking direction in, e.g., the visualization code, it's easier to put the direction in the config file.
Now that's changed, we don't need to specify "forwardtrack" or "backtrack" anymore in the CLI. Closes #328

### CODE REVIEW

**Comment by Peter9192** [comment]
I'm all for this. Just wonder if 'tracking direction' is the best name for the new config setting. I was thinking of 'tracking mode' as an alternative. 

@ruudvdent are time and distance tracking alternative modes or additional options for a forward or backward run?

**Comment by ruudvdent** [comment]
I think tracking direction is clear, mode would be fine as well, so no particular preference from my side. Time and distance tracking would rely on the basic tracking in either direction for the calculations, so they would be additional options.

**Comment by Peter9192** [comment]
ok let's stick with direction then. Can this be merged?

**Review by Peter9192 — APPROVED** [review]
I tried running the example floodcase again, and this works nicely. Note that we need to update the example config [here](https://rebrand.ly/wam2layers-example-data) as well.

**Comment by Peter9192** [comment]
> I tried running the example floodcase again, and this works nicely. Note that we need to update the example config [here](https://rebrand.ly/wam2layers-example-data) as well.

I have updated this file

**Pull request merged**
