### PR TITLE
Update README

### LINKED ISSUE #3: Document how to run the code
It would be nice to briefly describe (e.g. in the README) how to run the code. For example:

```
1. Download ERA5 data (which variables, ...) and store them using the following filenames.
2. Update lines 40-78 in the file `backtrack_savedaily_mat.py`
3. Execute the code with the following command: `python backtrack_savedaily_mat.py`
```

### PR DESCRIPTION
**Pull request by Peter9192**
- More descriptive title
- Add section on how to use
- Add section referring to other version of the code
- Add section on using/referencing this code

closes #3

### CODE REVIEW

**Comment by Imme1992** [comment]
Good idea to make a more complete Readme file

**Comment by Peter9192** [comment]
@Imme1992 do you want to do a quick check whether you're happy with this updated README file?

Preview: https://github.com/WAM2layers/WAM2layers/tree/update-readme

**Review by Imme1992 — APPROVED** [review]
New readme structure looks good, I made some small changes (precipitation is actually the total precipitation, but it might be that the variable name is different in the file)

**Comment by Peter9192** [comment]
Thanks for reviewing!

**Pull request merged**
